GET http://localhost:3000/api/v1/posts/21/comments

##

POST http://localhost:3000/api/v1/posts/21
Content-Type: application/json

{
  "data": {
    "title": "New Post",
    "body": "New Post Body"
  }
}       